global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'Ecom_api_gateway'
    static_configs:
      - targets: ['localhost:5000']

  - job_name: 'Ecom_product_service'
    static_configs:
      - targets: ['localhost:5268']

  - job_name: 'Ecom_auth_service'
    static_configs:
      - targets: ['localhost:5269']
